### ISSUE TITLE
Suggestion: Show example output in the readme file

### ISSUE THREAD

**Issue by LiorBanai** [cocowalla/serilog-sinks-file-header#4]
Hi,
I may add parsing of the header in my [Serilog parser](https://github.com/Analogy-LogViewer/Analogy.LogViewer.Serilog) for  my [Analogy log viewer](https://github.com/Analogy-LogViewer/Analogy.LogViewer).
I suggest to update the readme with example of input and output (or even in unit test) so it will be easier to integrate your work  in other projects.
Could be related to out repositories like the compressed file repos.
I plan to add support for compressed file in my viewer :)

**Comment by cocowalla** [comment]
I'm not sure it would make sense to add an example to the readme, as this projects doesn't add a standard header - it's completely up to the caller to tell it what header to write (can be a string, or a Func<string>). Your header can be an [ASCII Rick Roll](http://www.asciify.net/ascii/show/8643) if you really want :laughing: 

Serilog message templates are also completely customisable; while there is a default, there is no one size fits all so its very common to change it. Furthermore, Serilog message templates typically only use a space character to delimit fields (although this is of course customisable :smile:).

But now you've given me the idea, it would be interesting to see if it's possible to automatically write a standardised header based on the message template. Getting access to the template is likely to be problematic tho, as Serilog doesn't expose sinks and configs at runtime... *might* be possible to get this during building of the ILogger, though it's likely to be ugly :smile:

Your log parser looks interesting BTW. I generally just use a text editor and some regex-foo to filter to what I want, but an actual UI and a ability to save patterns could be pretty useful!

**Comment by LiorBanai** [comment]
I see. So there is no point in adding example indeed to the readme 🙂.

Thanks for explaining in detail 👍
